# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-25 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bid', models.FloatField()),
                ('bidType', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
                ('bidtypes', models.CharField(choices=[('cpc', 'cpc'), ('cpm', 'cpm'), ('cpa', 'cpa'), ('cpv', 'cpv'), ('cpi', 'cpi')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_task.Channel'),
        ),
    ]
