# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-26 20:05
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='bidType',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='channel',
            name='bidtypes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None),
        ),
        migrations.AlterField(
            model_name='channel',
            name='slug',
            field=models.CharField(max_length=15),
        ),
    ]
