# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-26 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_task', '0002_auto_20170726_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='bidtypes',
            field=models.CharField(max_length=50),
        ),
    ]
