# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-26 23:29
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_task', '0003_auto_20170727_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='bidtypes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None),
        ),
    ]
